version: "3.8"

services:
  fastapi-app:
    build: .
    container_name: fastapi-jars
    ports:
      - "6969:6969"
    volumes:
      - ./jars_data.db:/app/jars_data.db  # Persist the SQLite database
    restart: unless-stopped
