name: FastAPI Server Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-server:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Start the FastAPI server in the background
      - name: Start FastAPI server
        run: |
          nohup uvicorn app.server:app --host 0.0.0.0 --port 6969 > server.log 2>&1 &
          echo $! > server.pid  # Save the process ID
          sleep 10  # Wait for the server to start

      # Check if the server is running
      - name: Check if server is up
        run: |
          curl --fail http://localhost:6969 || exit 1

      # Shut down the FastAPI server (even if the previous steps fail)
      - name: Shut down FastAPI server
        if: always()
        run: |
          if [ -f server.pid ]; then
            kill $(cat server.pid) || true
            rm server.pid
          fi
          pkill -f uvicorn || true  # Ensure the server is stopped
