name: FastAPI Server Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-server:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Start FastAPI server
      run: |
        nohup uvicorn app.server:app --host 0.0.0.0 --port 6969 &
        sleep 10  # Wait for the server to be up

    - name: Check if server is up
      run: |
        curl --fail http://localhost:6969 || exit 1

    - name: Shut down FastAPI server
      if: always()
      run: |
        pkill -f uvicorn

