name: FastAPI Server Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-server:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:15
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpassword
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U testuser" 
          --health-interval=10s 
          --health-timeout=5s 
          --health-retries=5

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build and run the FastAPI server
      run: |
        docker-compose up -d
        sleep 10  # Wait for the server to be up

    - name: Check if server is up
      run: |
        curl --fail http://localhost:8000 || exit 1

    - name: Shut down services
      if: always()
      run: docker-compose down

